### ISSUE TITLE
')' character is missing and needs to be fixed

### ISSUE THREAD

**Issue by mr-xhunt** [bug-vs-me/nuclei#1]
The issue is on line: 

> response=$(curl -s -X GET -u "$API_USERNAME:$API_KEY" -H 'Accept: application/json' "https://api.hackerone.com/v1/hackers/programs/$handle" | jq -r '.relationships.structured_scopes.data[] | select(.attributes.asset_type == "URL" or select(.attributes.asset_type == "WILDCARD" and .attributes.eligible_for_submission == true) | .attributes.asset_identifier')

after **submission ==true** one more **)** is required.

**Comment by bug-vs-me** [comment]
`response=$(curl -s -X GET -u "$API_USERNAME:$API_KEY" -H 'Accept: application/json' "https://api.hackerone.com/v1/hackers/programs/$handle" | jq -r '.relationships.structured_scopes.data[] | select(.attributes.asset_type == "URL" or select(.attributes.asset_type == "WILDCARD" and .attributes.eligible_for_submission == true) | .attributes.asset_identifier')`

this is correct 

please share any error screenshot

**Comment by mr-xhunt** [comment]
This error happens when I use your code and after adding **)** character after **submission == true** the error is solved

![syntax-error](https://user-images.githubusercontent.com/61092858/235462392-82c8a594-029e-4f27-8303-b2104e6925ac.png)
